### ISSUE TITLE
Opening table on server causes server crash 1.15.2

### ISSUE THREAD

**Issue by PanoptesDreams** [TeamAOF/Artis#18] opened 2020-03-26 02:41 UTC
[title]

**Comment by LemmaEOF** [comment] 2020-03-26 02:58
Please provide a crash log.

**Comment by PanoptesDreams** [comment] 2020-03-26 09:35
---- Minecraft Crash Report ----
// My bad.

Time: 26/03/20 10:34 PM
Description: Watching Server

java.lang.Error
	at net.minecraft.class_3178.run(class_3178.java:48)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at net.minecraft.class_3178.run(class_3178.java:48)

-- Thread Dump --
Details:
	Threads: "WorldEdit Session Saver - 0" Id=1071 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@30a2b0d2
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@30a2b0d2
	at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
	at java.util.concurrent.LinkedBlockingDeque.pollFirst(Unknown Source)
	at java.util.concurrent.LinkedBlockingDeque.poll(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...


"Netty Server IO #3" Id=1060 RUNNABLE
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@3e6558b6
	-  locked java.util.Collections$UnmodifiableSet@3a5adba2
	-  locked sun.nio.ch.WindowsSelectorImpl@7f58528d
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
	...


"Netty Server IO #2" Id=1059 RUNNABLE
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@5ad95994
	-  locked java.util.Collections$UnmodifiableSet@4e6d0a91
	-  locked sun.nio.ch.WindowsSelectorImpl@22065f35
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
	...


"Netty Server IO #1" Id=1058 RUNNABLE
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@1f77adc2
	-  locked java.util.Collections$UnmodifiableSet@f725241
	-  locked sun.nio.ch.WindowsSelectorImpl@29edf8bc
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
	...


"Java2D Disposer" Id=1049 WAITING on java.lang.ref.ReferenceQueue$Lock@3902f543
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@3902f543
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at sun.java2d.Disposer.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


"Server Watchdog" Id=1047 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
	at net.minecraft.class_3178.run(class_3178.java:45)
	at java.lang.Thread.run(Unknown Source)


"Resource IO {0}" Id=1025 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1b39561c
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1b39561c
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
	at java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


"Netty Server IO #0" Id=1024 RUNNABLE
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@6c4ef60
	-  locked java.util.Collections$UnmodifiableSet@40aadf1c
	-  locked sun.nio.ch.WindowsSelectorImpl@6e2c92a7
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
	...


"ObjectCleanerThread" Id=1023 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@3f74a0c8
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@3f74a0c8
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)


"DestroyJavaVM" Id=1022 RUNNABLE


"Server console handler" Id=1021 RUNNABLE (in native)
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	-  locked java.io.BufferedInputStream@1eeae7a9
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	-  locked java.io.InputStreamReader@8ae9957
	at java.io.InputStreamReader.read(Unknown Source)
	...


"Timer-191" Id=213 TIMED_WAITING on java.util.TaskQueue@21d9b4f
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@21d9b4f
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)


"Server Infinisleeper" Id=212 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at net.minecraft.class_3176$1.run(class_3176.java:94)


"Snooper Timer" Id=210 WAITING on java.util.TaskQueue@18751924
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@18751924
	at java.lang.Object.wait(Unknown Source)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)


"Attach Listener" Id=5 RUNNABLE


"Signal Dispatcher" Id=4 RUNNABLE


"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@516b722c
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@516b722c
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)


"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@2df33d77
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@2df33d77
	at java.lang.Object.wait(Unknown Source)
	at java.lang.ref.Reference.tryHandlePending(Unknown Source)
	at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)



Stacktrace:
	at net.minecraft.class_3178.run(class_3178.java:48)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4694866176 bytes (4477 MB) / 6091177984 bytes (5809 MB) up to 6091177984 bytes (5809 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xms4G -Xmx6G
	Fabric Mods: 
		adamantine: Adamantine 1.1.1
		adorn: Adorn 1.8.0+1.15.2
		allure: Allure 1.1.7
		alwaysdroploot: Always Drop Loot 3.6.0+mc1.14.4
		aquarius: Aquarius 1.4.0+1.15
		artifice: Artifice 0.6.0+1.15.2
		artis: Artis 1.2.0+1.15.2
		atmosfera: Atmosfera 1.2.0
		autoconfig1u: Auto Config v1 Updated 1.2.4
		bamboo-spikes-justfatlard: Bamboo Spikes 0.1.0
		better_wither_skeletons: Better Wither Skeletons 1.0.0
		betterthanmending: BetterThanMending 1.1.1
		bigbuckets: Big Buckets 1.1.0
		biow0rks: biow0rk5 0.4.0
		blue_endless_jankson: jankson +
		bowinfinityfix: Bow Infinity Fix rv8
		brokenxp: Broken XP 1.0.4
		bunch-o-trinkets: Bunch O' Trinkets 1.0.0
		cardinal-components-base: Cardinal Components API 2.3.0
		cardinal-components-block: Cardinal Components API 2.3.0
		cardinal-components-entity: Cardinal Components API 2.3.0
		cardinal-components-level: Cardinal Components API 2.3.0
		cardinal-components-world: Cardinal Components API 2.3.0
		chunkactivator: Chunk Activator 1.2.0+mc1.14.4
		clipboards: Clipboards 1.0.0+1.15.2
		cloth-basic-math: Cloth Basic Math 0.4.1
		cloth-config2: Cloth Config v2 2.11.2
		coloredfire: Colored Flames 1.1.9r1+1.15.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compressedblocks: Compressed Blocks 0.3
		cotton: Cotton 1.0.2
		cotton-cauldron: Cotton Cauldron 1.0.0-rc.6
		cotton-commons: Cotton Commons 1.0.0-rc.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.1
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		couplings: Couplings 1.3.1
		craftingpad: Crafting Pad 1.0.4
		eggtab: Egg Tab 1.1.2+1.15-1.16
		enderbox: Ender Box 1.0.1
		endershulkers: Ender Shulkers 1.0.0+1.15.2
		endfestation: Endfestation 1.0.0
		expandedstorage: ExpandedStorage 3.8.34+1.15.2
		expandedstorageapi: ExpandedStorageAPI 0.0.4+1.15.2
		extradoors: ExtraDoors 1.6.0-1.15
		fabric: Fabric API 0.5.1+build.294-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825de7
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825de7
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d0c
		fabric-furnaces: Fabric Furnaces 1.2.0
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
		fabric-language-kotlin: Fabric Language Kotlin 1.3.61+build.1
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d0c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.9+d249f7b6d1
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c30c
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabricessentials: fabricessentials 1.1.7
		fabricloader: Fabric Loader 0.7.8+build.189
		fairenchanting: FairEnchanting 1.1.2
		fatxporbs: Fat Experience Orbs 0.0.6
		fermion-modkeys: Fermion Modifier Keys 1.5.148
		firedchainmail: Fired Chainmail 1.0.0
		flonters: Flonters 1.0.2+1.15.1
		floradoubling: Flora Doubling 1.0.0
		gamemodeoverhaul: GamemodeOverhaul 1.15.2-1.0.1.6
		glassential: Glassential 1.15.1-1.1.3
		glowingbeds: Glowing Beds 1.0.2
		godown: Go Down 0.2.0+1.15
		goml: Get Off My Lawn 1.0.0-beta
		grandeconomy: Grand Economy 1.5.2
		harvest: Harvest 1.0.4
		illuminations: Illuminations 0.4.0
		immersive_portals: Immersive Portals 0.20
		ironbarrels2: Iron Barrels 2 2.3.0
		jankson: Jankson 2.0.1+j1.2.0
		jargm: Just Another Redstone Gate Mod 1.1.1
		kayak: kayak 0.1.1.22
		kirin: Kirin UI 1.5.2-1.15.2
		kyrptconfig: Kytpt Config 1.0.0
		lakeside: Lakeside 1.0.0+1.15.2
		leaf-decay: Leaf Decay ${version}
		libblockattributes: LibBlockAttributes 0.6.6
		libblockattributes_core: LibBlockAttributes (Core) 0.6.6
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.6.6
		libblockattributes_items: LibBlockAttributes (Items) 0.6.6
		libcd: LibCapableData 2.3.0+1.15.2
		libgui: LibGui 1.5.1
		lithium: Lithium 0.4.6
		llamasteeds: Llama Steeds 2020.1.10
		mambience: MAmbience 1.0.0
		me_shedaniel_cloth_basic-math: basic-math 0.3.0
		me_zeroeightsix_fiber: fiber 0.8.0-SNAPSHOT
		minecraft: Minecraft 1.15.2
		ml3api: ML3API 1.3.3
		mm: Manningham Mills 2.0
		mo_glass: Mo Glass 1.2-MC1.15
		moenchantments: Mo'Enchantments 1.9.6
		mooblooms: Mooblooms 1.1.1
		moretotems: More Totems 1.0.0
		nbtcrafting: NBT Crafting 1.2.15+1.15.1
		netherhigher: netherHigher 1.0.2+build.3
		ninjaphenix-container-lib: NinjaPhenix's Container Library 0.1.5+1.15.2
		org_aeonbits_owner_owner: owner 1.0.8
		org_apache_commons_commons-compress: commons-compress 1.9
		org_jetbrains_annotations: annotations 18.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.61
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.61
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.61
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.61
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.3
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.3
		oysters: Oysters fabric-0.1.4-1.15.1
		oysterscooking: Oysters Cooking 0.2.3b
		passable-leaves: Passable Leaves 0.3.0
		permafrost: Permafrost 1.3.1+1.15.1
		phosphor: Phosphor 0.4.2
		playerabilitylib: Pal 1.0.0
		programmerartinjector: Programmer Art Injector 1.1.0
		quickshulker: Quick Shulker 1.1.3
		reach-entity-attributes: Reach Entity Attribute 1.0.0
		roughlyenoughitems: Roughly Enough Items 3.6.4
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		shulkercharm: Shulker Charm 1.1.2+1.15.2
		simplystrawberrys: Simply Strawberries 1.0
		sit: Sit 1.15-4
		smith_and_fletch: Smith And Fletch 1.0.0
		sneakthroughberries: Sneak Through Berries 1.0.1
		sonyikaarftl: Advanced Rotten Flesh to Leather 1.4.4
		soulshards: Soul Shards Respawn 1.2.0
		spiceoffabric: Spice of Fabric 1.2.3+1.15.2
		spinnery: Spinnery 2.0.0+fabric-20w06a
		statement: Statement 2.1.2+20w11a
		staticdata: Static Data 1.1.2
		statskeeper: Stats Keeper 1.1.4
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		strongandfairanvils: Strong and Fair Anvils 0.3.0+1.15
		terraform: Terraform 1.4.3+build.29
		terrestria: Terrestria 1.2.1+build.29
		textile_backup: Textile Backup 1.1.0-1.15
		the_bumblezone: The Bumblezone - Fabric 1.0.1-1.15.2
		the_loved_ones: The Loved Ones 1.0.0-1.15.2
		tinyconfig: TinyConfig 1.1.2
		tinyfuel: Tiny Fuel 0.2.1
		toughglass: Tough Glass 1.1.0
		towelette: Towelette 3.1.4+20w11a
		trapexpansion: Trap Expansion 1.3.1
		traverse: Traverse 2.1.11+build.23
		trinkets: Trinkets 2.4.1
		tweed: Tweed API 2.2.8
		universalcomponents: Universal Components 0.4.4+1.15.2
		vanilla-hammers: Vanilla Hammers 1.7.0
		vanilla-toolsets: Vanilla Toolsets 1.2.2
		varlight: VarLight 1.3
		villagerhats: Villager Hats fabric-1.15.0-1.0.0
		walljump: Wall-Jump! 1.3.3+1.15
		wildworld: Wild World 1.2.0+1.15
		worldedit: WorldEdit 7.1.0;8e55131
		wrenchable: Wrenchable 0.2.2+1.15.2
		wrenchanything: Wrench Anything 1.1.3+1.15.2
	Player Count: 0 / 10; []
	Data Packs: vanilla, fabric/adamantine (incompatible), fabric/adorn (incompatible), fabric/alwaysdroploot (incompatible), fabric/aquarius (incompatible), fabric/bamboo-spikes-justfatlard (incompatible), fabric/better_wither_skeletons (incompatible), fabric/bigbuckets (incompatible), fabric/bunch-o-trinkets (incompatible), fabric/chunkactivator (incompatible), fabric/clipboards (incompatible), fabric/coloredfire (incompatible), fabric/compressedblocks (incompatible), fabric/cotton-commons (incompatible), fabric/craftingpad (incompatible), fabric/enderbox (incompatible), fabric/expandedstorage (incompatible), fabric/extradoors (incompatible), fabric/fabric-furnaces (incompatible), fabric/fabric-mining-levels-v0 (incompatible), fabric/firedchainmail (incompatible), fabric/flonters (incompatible), fabric/glassential (incompatible), fabric/goml (incompatible), fabric/harvest (incompatible), fabric/illuminations (incompatible), fabric/ironbarrels2 (incompatible), fabric/jargm (incompatible), fabric/kayak, fabric/libcd (incompatible), fabric/mo_glass (incompatible), fabric/mooblooms (incompatible), fabric/moretotems (incompatible), fabric/oysters (incompatible), fabric/oysterscooking (incompatible), fabric/shulkercharm (incompatible), fabric/simplystrawberrys (incompatible), fabric/sonyikaarftl (incompatible), fabric/soulshards (incompatible), fabric/strongandfairanvils (incompatible), fabric/terrestria (incompatible), fabric/tinyfuel (incompatible), fabric/toughglass (incompatible), fabric/towelette (incompatible), fabric/trapexpansion (incompatible), fabric/traverse (incompatible), fabric/vanilla-hammers (incompatible), fabric/vanilla-toolsets (incompatible), fabric/villagerhats (incompatible), fabric/wildworld (incompatible), fabric/wrenchanything (incompatible), global/cotton_generated (incompatible), fabric/endershulkers (incompatible), global/yggdrasil (incompatible), fabric/spiceoffabric (incompatible), fabric/the_bumblezone (incompatible), global/UsefulComposter.zip (incompatible), global/Yggdrasil - Crafting Recipies - VanillaTweaks_c710914.zip (incompatible), global/afk display v1.0.1.zip (incompatible), global/customizable armor stands v2.5.0.zip, global/double shulker shells v1.0.3.zip (incompatible), global/dragon drops elytra v1.0.2.zip (incompatible), global/larger phantoms v1.0.0.zip (incompatible), global/more mob heads v2.2.0.zip (incompatible), global/player head drops v1.0.0.zip (incompatible), global/treasure gems v1.0.0.zip (incompatible), global/wandering trades v1.0.0.zip, global/wither-fortress-e3500.zip (incompatible), fabric/allure (incompatible)
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by PanoptesDreams** [comment] 2020-03-26 09:35
sorry took a while. had to rebuild my sever and hoped that would fix it.. no sadly

**Comment by LemmaEOF** [comment] 2020-03-26 09:39
oh boy.

**Comment by PanoptesDreams** [comment] 2020-03-26 09:41
I can usually somewhat read these, but this is beyond me..

**Comment by LemmaEOF** [comment] 2020-03-26 09:42
yeah, this is a network issue, which are thoroughly unreadable. Can you try and see if this still happens if you *only* have artifice in?

**Comment by PanoptesDreams** [comment] 2020-03-26 09:55
it does indeed

**Comment by PanoptesDreams** [comment] 2020-03-26 09:55
[crash-2020-03-26_22.52.34-server.txt](https://github.com/AllOfFabric/Artis/files/4386388/crash-2020-03-26_22.52.34-server.txt)

**Comment by LemmaEOF** [comment] 2020-03-26 09:56
OH THANK GOD, A SENSIBLE ERROR.

**Comment by LemmaEOF** [comment] 2020-03-26 09:57
ahh, it can't find the `ContainerScreen` class from the dedicated server. That makes sense, since it's not *supposed* to be on a dedicated server. Easy fix; I'll get to it when I've got time.

**Comment by Shrimpstress** [comment] 2020-07-24 05:50
I'm closing this because I assume the issue is no longer present. Re-open this if you encounter the issue again.

**Closed as completed by Shrimpstress** 2020-07-24 05:50 UTC
